server.port=${NOTIFICATION_SERVICE_PORT:8081}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID:notification-service}
spring.kafka.consumer.auto-offset-reset=${KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}

app.kafka.user-events-topic=${USER_EVENTS_TOPIC:user-events}